### PR TITLE
boot_archive_configure can fail on old system

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Comment by pyhalov** [comment]
Seems to be correct. The only suspicious thing is use of non-documented devfsadm option. @tsoome: What do you think?

**Comment by tsoome** [comment]
For quick fix it seems ok, but -r should apply to module path as well, so the real fix would be to investigate why module path is not updated by -r.

**Comment by pyhalov** [comment]
Well, it behaves as documented:
```
       -r root_dir
                          Presume that the /dev directory trees are found
                          under root_dir, not directly under root (/). No
                          other use or assumptions are made about root_dir.
```

**Comment by tsoome** [comment]
ahm, well, indeed, the idea is that we want to run modules from current system, not from root_dir, so yes, this use of -l is a bit dubious.... we can not ensure the modules are actually usable.

**Comment by pyhalov** [comment]
@keremet 
From IRC log:
```
<alp_> tsoome: Hi. Do you mean that new devfsadm and new link modules can misbehave with old kernel? 
<tsoome> kernel or userland
<alp_> But if we use old devfsadm, it could create something incompatible to new kernel?
<tsoome> thats the same issue as running anything from alternate image
<tsoome> it may, since those interfaces are quite static, the probability is small, but there is no way to tell.
<alp_> So do you suggest to use devfsadm from base image? 
<alp_> (build host)
<tsoome> yep. and yes, it means the build host should be kept up-to-date
<alp_> I don't see good solution here, as using devfsadm from old system we can skip some links for new devices
```

**Comment by pyhalov** [comment]
Andw we use new svccfg... without caring for it requiring newer libc.so... Now I'm confused about which tools should be used.

**Comment by pyhalov** [comment]
As I see from history, devfsadm from new image has always been used to create boot root. I'm not convinced that using old one is much better idea. So I'll merge this as is for now.

**Pull request merged**
