### PR TITLE
slim_source: sparc fixes

### PR DESCRIPTION
**Pull request by tsoome**
Fix some issues: gcc can not grok studio flags and missing prototype.

### CODE REVIEW

**Review by AndWac — DISMISSED** [review]

**Review by AndWac — COMMENTED** [review]
Sorry, only saw it after my approve: Did you work on the latest revision?
There are some missing lines.

**Comment by tsoome** [comment]
> Sorry, only saw it after my approve: Did you work on the latest revision?
> There are some missing lines.

apparently it was not, fixed.

**Review by AndWac — APPROVED** [review]

**Comment by pyhalov** [comment]
Interesting, how much work is required to make text installer actually work on sparc...

**Comment by tsoome** [comment]
> Interesting, how much work is required to make text installer actually work on sparc...

It should not be too much into hw specific, but atm we need to get prerequisites...

**Pull request merged**
