### PR TITLE
Py3 

### PR DESCRIPTION
**Pull request by pyhalov**
Now it publishes. And I'm sure doesn't work as expected ;)

### CODE REVIEW

**Comment by pyhalov** [comment]
Last error from distro_const:
```
Traceback (most recent call last):
  File "/usr/share/distro_const/im_pop.py", line 379, in <module>
    DEFAULT_MAIN_URL)
  File "/usr/lib/python3.5/vendor-packages/osol_install/distro_const/dc_utils.py", line 55, in get_manifest_value
    node_list = manifest_obj.get_values(path, is_key)
  File "/usr/lib/python3.5/vendor-packages/osol_install/ManifestRead.py", line 157, in get_values
    self.client_sock.send(pre_request)
TypeError: a bytes-like object is required, not 'str'
Exception ignored in: <bound method ManifestRead.__del__ of <osol_install.ManifestRead.ManifestRead object at 0xfffffd7feeb82470>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/vendor-packages/osol_install/ManifestRead.py", line 105, in __del__
TypeError: a bytes-like object is required, not 'str'
Child returned err 1
Build completed Tue Dec 10 23:32:26 2019
Build failed.
```

**Comment by pyhalov** [comment]
```
Build completed Wed Dec 11 18:42:07 2019
Build is successful.
Server terminating
Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stdout>'> at interpreter shutdown, possibly due to daemon threads

Thread 0x0000000000000002 (most recent call first):
  File "/usr/lib/python3.5/vendor-packages/osol_install/ManifestServ.py", line 870 in __socket_server_main

Current thread 0x0000000000000001 (most recent call first):
Abort (core dumped)
```

**Comment by pyhalov** [comment]
Installing from minimal image using text installer works at this point (including zpool install).

**Comment by pyhalov** [comment]
I've found an issue in gui installer fix and now it works. This means I think this code is ready. However, I'd appreciate review and testing.

**Comment by pyhalov** [comment]
@tsoome, can you have a look on it?
 
Going to merge as 4 commits 

- Remove libaiscf
- Remove liberrsvc
- Conversion to Py3/64-bits
- Add distro_const -d option to enable Manifest Server socket debug mode

**Comment by Mno-hime** [comment]
I read the change, but Python is peanuts for me. I guess those "xxx_todo_changeme16" are still waiting for something? Otherwise, merge whenever you feel like to, I'll at some point build images and test installation.

**Comment by Mno-hime** [comment]
At the end of the installation I get this when installing via the GUI installer (as seen in `~/.xsession-errors`):
```
Exception ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 1287, in _shutdown
    assert tlock.locked()
AssertionError: 
pkg: info: no packages matching the following patterns you specified are
installed on the system.  Try querying remotely instead:

        entire
pkg: info: no packages matching the following patterns you specified are
installed on the system.  Try querying remotely instead:

        entire
```

**Comment by Mno-hime** [comment]
I get this with Minimal ISO when "Use a partition of the disk (MBR)" is selected ("Use whole disk (EFI)" is fine):
```
2019-12-18 08:27:56,359 - INFO    : text-install:120 **** START ****
2019-12-18 08:28:08,039 - ERROR   : text-install:254 Install Profile:
Disk Info (c3t0d0):
Size: 16.0gb
BE name: openindiana
Overwrite boot configuration: True
None
None
None
2019-12-18 08:28:08,057 - ERROR   : text-install:255 Traceback (most recent call last):
  File "/usr/bin/text-install", line 236, in <module>
    SCREEN = SCREEN.show(INSTALL_PROFILE)
  File "/usr/lib/python3.5/vendor-packages/osol_install/text_install/base_screen.py", line 126, in show
    return self.validate_loop()
  File "/usr/lib/python3.5/vendor-packages/osol_install/text_install/base_screen.py", line 156, in validate_loop
    self.on_continue()
  File "/usr/lib/python3.5/vendor-packages/osol_install/text_install/fdisk_partitions.py", line 266, in on_continue
    self.disk_info.create_partitioned_layout()
  File "/usr/lib/python3.5/vendor-packages/osol_install/profile/disk_info.py", line 593, in create_partitioned_layout
    maxsz = min(self.get_size(), SliceInfo.MAX_VTOC)
TypeError: unorderable types: DiskSpace() < DiskSpace()

2019-12-18 08:28:08,060 - INFO    : text-install:99 **** END ****
```

**Comment by pyhalov** [comment]
> At the end of the installation I get this when installing via the GUI installer (as seen in `~/.xsession-errors`):
> 
> ```
> Exception ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/threading.py", line 1287, in _shutdown
>     assert tlock.locked()
> AssertionError: 

Don't see where it coming from, will check.

> pkg: info: no packages matching the following patterns you specified are
> installed on the system.  Try querying remotely instead:
> 
>         entire
> pkg: info: no packages matching the following patterns you specified are
> installed on the system.  Try querying remotely instead:
> 
>         entire
> ```
These are fine, gui installer does "pkg info entire", and as entire is not on test iso, you get these warnings.

**Comment by Mno-hime** [comment]
`TypeError: unorderable types: DiskSpace() < DiskSpace()` is fixed, `assert tlock.locked()` present. No other problems identified.

**Comment by pyhalov** [comment]
The exception seems to be coming from libtransfer_pymod, something is wrong with its way of saving/restore thread state.

**Comment by Mno-hime** [comment]
> > At the end of the installation I get this when installing via the GUI installer (as seen in `~/.xsession-errors`):
> > ```
> > Exception ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
> > Traceback (most recent call last):
> >   File "/usr/lib/python3.5/threading.py", line 1287, in _shutdown
> >     assert tlock.locked()
> > AssertionError: 
> > ```
> 
> Don't see where it coming from, will check.

It's gone. Thanks.

**Pull request merged**
